owner: crewlinker # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Crewlinker API
    url: api.crewlinker.com
  - name: Crewlinker WEB
    url: https://crewlinker.com
  # - name: Fail Test API # This will fail and notify you via slack and assign the issue on GitHub
  #   url: https://httpstat.us/500

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Setting uptime for crewlinker.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - advanderveer
  - gurkanguray

user-agent: crewlinker

